name: Docker Image

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker image build -t mmbesar/mkdocs:latest .
        docker push ghcr.io/mmbesar/mkdocs:latest
